language: node_js
node_js:
  - "8"
go: 
  - "1.9"
env:
  global:
    - CI=true
    - NODE_ENV=production
script:
  - cd client
  - yarn
  - yarn lint
  - yarn unit
  - yarn build
  - cd ../server
  - go get
  - go build